### PR TITLE
Update URLs to all of fpottier packages

### LINKED ISSUE #93: menhir, menhirLib and menhirSdk have bad checksum
https://github.com/ocamllabs/vscode-ocaml-platform/runs/2617568131?check_suite_focus=true

### PR DESCRIPTION
**Pull request by smorimoto**
Fixes #93

### CODE REVIEW

**Comment by Niols** [comment]
Thank you! I would say this PR is a bit urgent as, for now, no package that uses Menhir (or a dependency that uses Menhir) will be able to build on Windows.

**Comment by fdopen** [comment]
fixed via a62521e0d04814c32b0f9c3f7f51095847a09198

**Comment by smorimoto** [comment]
Thanks @fdopen!

**Comment by Niols** [comment]
Yes, thanks!

**Pull request closed without merging**
