### PR TITLE
Make more packages compile

### PR DESCRIPTION
**Pull request by samoht**
These patches (plus some pins that I'll try to upstream soon) make irmin compile on cygwin. Not sure how to test these better. All of this is pretty ugly...

### CODE REVIEW

**Comment by fdopen** [comment]
Thanks,
However, git's win.diff seems to be missing. Please add it :)

oasis files are usually rewritten by my merge scripts, if the compilation fails because of this particular error. It just didn't work in this case because of the bashism in postconf...

CC is currently added by the compiler description to the environment. The environment variable is picked up by all autoconf-based build scripts, some versions of OCamlMakefile and many hand written configure scripts (like the one by zarith). So I wonder why this patch was necessary for you? If you use a system provider, please define CC manually. Otherwise many other packages won't build, too.

**Comment by samoht** [comment]
I'm using http://protz.github.io/ocaml-installer/ and I don't have my windows machine at hands. I'll check again (and add the missing file) next week. Thanks for the review!

Also, I have issues with too long command-line when linking the final irmin binaries, not sure how to fix that... If you have any idea...

**Comment by fdopen** [comment]
Ok, I've cherry picked some of your commits. Open a new pull request for git if necessary.

17f3594938b46d12d423a6d128f61147616ddf71 is dubious. If the install file is removed, the files inside ${prefix}/bin won't be removed. Perhaps the files are copied twice, the first time by 'ocaml setup.ml -install', the second time by opam. So what? Or possibly a problem of the opam build shipped by the ocaml-installer (two versions, one with exe suffix, one without?), but it doesn't happen with my builds of opam.

commend-line length limit: 

After I've added https://github.com/mirage/ocaml-crunch/pull/16 , I was able to build irmin without problems. However, the results of your test cases don't look very promisingly at all...

Try my build of flexlink, it's a patched version. (You can't install flexlink through opam because of circular dependencies. You have to extract its files from one of the tar.xz files linked at https://github.com/fdopen/opam-repository-mingw/blob/master/README.md . )
There are already several open Mantis bug tickets about it ( the latest one: http://caml.inria.fr/mantis/view.php?id=7050 ) The fundamental problem must be solved upstream by a change in the command line interface of ocaml (and tools like ocamlfind, ocamlbuild, etc. must honor it), but a few problems can be circumvented by patching just flexlink.

**Comment by samoht** [comment]
> Perhaps the files are copied twice, the first time by 'ocaml setup.ml -install', the second time by opam. So what? Or possibly a problem of the opam build shipped by the ocaml-installer (two versions, one with exe suffix, one without?), but it doesn't happen with my builds of opam.

yes that's the issue. Where can I find your build of opam? Should I rebuild it from scratch?

> I was able to build irmin without problems. However, the results of your test cases don't look very promisingly at all...

great! how did you do that? :-) did you try to install `irmin-unix`? I'm keen to fix the tests, I think there are quite a few issues with path management...

And I'll try your flexink version.

Thanks for the porting effort, that's very useful!

**Comment by fdopen** [comment]
On Mon, 15 Feb 2016 13:23:44 -0800
Thomas Gazagnaire wrote:

> yes that's the issue. 

I hit this problem two or three times, than I've decided to patch it
away at the opam level for the moment. (Of course, it's dirty. You can't
have any longer bin/foo and bin/foo.exe, or bad things can happen, like
under cygwin. But fixing it in each single package description is too
bugging,... )

> Where can I find your build of opam? Should I rebuild it from scratch?

not completely from scratch. If you already used the git from the
cygwin distribution, I don't think it should be necessary. Just make
sure, that you remove the other ocaml/opam/ascpud/flexlink installation
from your terminal environment (PATH, OCAMLLIB, OCAMLFIND_CONF and
similar variables)

Then extract the opam32.tar.xz or opam64.tar.xz file and call the
install script as described in the Readme:
https://github.com/fdopen/opam-repository-mingw/blob/master/README.md#installation

Instead of `opam init ...`, just create a new switch (there are
precompiled OCaml builds for faster bootstrap, OCaml's makefiles are
not parallelizable under Windows):

``` 
opam switch install s -A 4.02.3+mingw64c # or 4.02.3+mingw32c
# a short name without + and . is preferable.
opam $(eval config env)
opam install depext depext-cygwinports 
export PATH="/usr/x86_64-w64-mingw32/sys-root/mingw/bin:${PATH}"
opam depext irmin-unix alcotest
opam install -b irmin-unix alcotest
```

> great! how did you do that? :-) did you try to install `irmin-unix`?
> I'm keen to fix the tests, I think there are quite a few issues with
> path management...

Yes, irmin-unix and 90% of all tests failed ...

**Comment by samoht** [comment]
Ok, I've reinstall OCaml on windows using the graphical installer from https://fdopen.github.io/opam-repository-mingw/installation This worked great, I manage to compile irmin-unix and run the unit-tests of Irmin. As expected, all the in-memory tests worked fine, the issue is with path-mangling when using the unix backend.

Then I tried to run the test binary from powershell. But no luck: the program just produces no output, without more information (even `test.exe -h` prints nothing) . I'm installing windbg to try to understand what happens but maybe that something which sounds familiar to you?

**Comment by fdopen** [comment]
Make sure that  `/usr/x86_64-w64-mingw32/sys-root/mingw/bin` or `/usr/i686-w64-mingw32/sys-root/mingw/bin` are in your $PATH from the powershell as well. It needs the zlib and gmp dlls from there - and not from somewhere else.

If you compiled to bytecode (and without '-custom), you must make sure that additional environment variables are set (the output of opam config env, without CPP, CC and PERL5LIB).

Just start the powershell from within a working cygwin shell:

`/cygdrive/c/path/to/powershell.exe`

and try it again. cygwin also manipulates other environment variable that will influence the behavior of your binaries (e.g. it will overwrite TEMP and TMP with C:\cygwinroot\tmp. If your windows versions of TEMP or TMP contains unicode chars, the ocaml runtime (Filename.open_temp_file , etc. ) can't deal with it,... )

**Comment by samoht** [comment]
I get it, thanks a lot! Is there a way to statically link the 2 dlls than I need? Ideally I just like to distribute a stand-alone binary to my users...

**Comment by samoht** [comment]
ok just copying the exe + the 2 DLLs on the same path works. I'm happy. That's a good motivation to use the pure OCaml version of zlib and split the fast SHA1 bits from nocrypto to not depends on zarith to not depend on gmp.

Thanks very much for your help, I'm closing the PR now!

**Comment by fdopen** [comment]
The link flags are usually hardcoded, gcc prefers the dynamic versions by default and it's ugly to tell flexlink how to link them properly.

But there is an easy workaround, which works for simple dependencies. Just remove the import libraries (temporary):

xz /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libz.dll.a
xz /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libgmp.dll.a

opam install ...

xz -d /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libgmp.dll.a.xz
xz -d /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libz.dll.a.xz

if gcc/ld can't find the these file, the static versions are used.

**Pull request closed without merging**
