### PR TITLE
Fix bad checksum for menhir packages

### LINKED ISSUE #93: menhir, menhirLib and menhirSdk have bad checksum
https://github.com/ocamllabs/vscode-ocaml-platform/runs/2617568131?check_suite_focus=true

### PR DESCRIPTION
**Pull request by smorimoto**
Fixes #93

### CODE REVIEW

**Comment by Niols** [comment]
This is not the right fix. The bad checksum comes from the fact that the URLs for downloading the archives are now being a login page (the checksum is that of the HTML login page and not of the archive). This has been reported to François Pottier who fixed it by changing the URLs of all his packages (but not the checksum) in https://github.com/ocaml/opam-repository/pull/18697

**Comment by smorimoto** [comment]
Oops, you are right.

**Comment by Niols** [comment]
It would be nice to have this issue fixed, however, but I am unsure how this works: should we suggest a PR or should we just wait to have this repository updated with ocaml/opam-repository 's changes?

**Comment by Niols** [comment]
Oh, you already posted #95, nevermind me. Thank you for the fix!

**Comment by smorimoto** [comment]
I just cherry-picked :) Thank you for letting me know!

**Pull request closed without merging**
